<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-06-24T18:20:00Z" name="OrangeHRM" finished-at="2021-06-24T18:20:15Z" duration-ms="15017">
    <groups>
    </groups>
    <test started-at="2021-06-24T18:20:00Z" name="Orange1" finished-at="2021-06-24T18:20:15Z" duration-ms="15017">
      <class name="com.orange.test.Login_MavenOrange">
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:com.orange.test.Login_MavenOrange@39de3d36]" started-at="2021-06-24T23:50:01Z" name="launchBrowser" finished-at="2021-06-24T23:50:09Z" duration-ms="7529" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="login_002()[pri:0, instance:com.orange.test.Login_MavenOrange@39de3d36]" started-at="2021-06-24T23:50:09Z" name="login_002" finished-at="2021-06-24T23:50:10Z" duration-ms="1426" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The error text is displayed expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The error text is displayed expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at com.orange.test.Login_MavenOrange.login_002(Login_MavenOrange.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_002 -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.orange.test.Login_MavenOrange@39de3d36]" started-at="2021-06-24T23:50:11Z" name="closeBrowser" finished-at="2021-06-24T23:50:15Z" duration-ms="4373" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.orange.test.Login_MavenOrange -->
    </test> <!-- Orange1 -->
  </suite> <!-- OrangeHRM -->
</testng-results>
